name: Release

on:
  push:
    branches:
      - master

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app (Windows)
        run: npm run tauri build

      - name: Prepare release assets
        shell: powershell
        run: |
          $outDir = "release-assets"
          New-Item -ItemType Directory -Path $outDir -Force

          # Skopiuj EXE
          Copy-Item "src-tauri/target/release/app.exe" "$outDir/MarkIt.exe"

          # Skopiuj MSI (pierwszy znaleziony)
          $msi = Get-ChildItem "src-tauri/target/release/bundle/msi/*.msi" | Select-Object -First 1
          Copy-Item $msi.FullName "$outDir/Installer.msi"

      - name: Release with semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
